[workspace]
members = [
    "pgext-cli",
    "pgext-hook-macros",
    "pgx_show_hooks",
    "pgx_trace_hooks",
    "pgextmgr",
]
exclude = [   
    "pgextworkdir",
]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
