[[plugins]]
name = "pgjwt"
version = "9742dab1b2f297ad3811120db7b21451bca2d3c9"
download_url_tar = "https://github.com/michelp/pgjwt/archive/9742dab1b2f297ad3811120db7b21451bca2d3c9.tar.gz"
resolver = "pgxs"
dependencies = ["pgcrypto"]

[[plugins]]
name = "pg_hint_plan"
version = "1.5.0"
download_url_zip = "https://github.com/ossc-db/pg_hint_plan/archive/refs/tags/REL15_1_5_0.zip"
resolver = "pgxs"
install_strategy = "preload+install"

[[plugins]]
name = "orafce"
version = "4.2.1"
download_url_tar = "https://github.com/orafce/orafce/archive/refs/tags/VERSION_4_2_1.tar.gz"
resolver = "pgxs"
install_strategy = "preload+install"

[[plugins]]
name = "pgaudit"
version = "1.7.0"
download_url_tar = "https://github.com/pgaudit/pgaudit/archive/refs/tags/1.7.0.tar.gz"
resolver = "pgxs"
install_strategy = "preload+install"

[[plugins]]
name = "pglogical"
version = "2.4.2"
download_url_tar = "https://github.com/2ndQuadrant/pglogical/archive/refs/tags/REL2_4_2.tar.gz"
resolver = "pgxs"
install_strategy = "preload+install"

[[plugins]]
name = "pg_bigm"
version = "1.2"
download_url_tar = "https://github.com/pgbigm/pg_bigm/archive/refs/tags/v1.2-20200228.tar.gz"
resolver = "pgxs"
install_strategy = "preload+install"

[[plugins]]
name = "pg_cron"
version = "1.5.1"
download_url_tar = "https://github.com/citusdata/pg_cron/archive/refs/tags/v1.5.1.tar.gz"
resolver = "pgxs"
install_strategy = "preload+install"

[[plugins]]
name = "pg_prewarm"
version = "0.0.0"
resolver = "pgsrctree"
no_download = true
install_strategy = "preload+install"

[[plugins]]
name = "auto_explain"
version = "0.0.0"
resolver = "pgxs"
copy_from_contrib = "auto_explain"
install_strategy = "preload"

[[plugins]]
name = "pgcrypto"
version = "0.0.0"
resolver = "pgsrctree"
no_download = true

[[plugins]]
name = "pg_stat_statements"
version = "0.0.0"
resolver = "pgsrctree"
no_download = true
install_strategy = "preload+install"

[[plugins]]
name = "pg_similarity"
version = "b9cb0a2d501b91e33cd1ef550b05483ca3563f71"
download_url_tar = "https://github.com/eulerto/pg_similarity/archive/b9cb0a2d501b91e33cd1ef550b05483ca3563f71.tar.gz"
resolver = "pgxs"
install_strategy = "preload+install"

[[plugins]]
name = "plprofiler"
version = "4.2.1"
download_url_tar = "https://github.com/bigsql/plprofiler/archive/refs/tags/REL4_2_1.tar.gz"
resolver = "pgxs"
install_strategy = "preload+install"

# [[plugins]]
# name = "neon"
# version = "0.0.0"
# download_git = { url = "https://github.com/neondatabase/neon", rev = "1401021", sub_path = "pgxn/neon" }
# resolver = "pgxs"
# Doesn't work with the original Postgres

[[plugins]]
name = "citus"
version = "11.2.0"
download_url_tar = "https://github.com/citusdata/citus/archive/refs/tags/v11.2.0.tar.gz"
resolver = "pgxs"
resolver_args = ["--without-lz4", "--without-zstd"]
install_strategy = "preload+install"

[[plugins]]
name = "pg_tiktoken"
version = "0.0.1"
download_git = { url = "https://github.com/kelvich/pg_tiktoken", rev = "801f84f" }
resolver = "pgx"


# TODO(yuchen): Error - sed: 1: "postgres.c": extra characters at the end of p command
# might be macOS vs GNU
# [[plugins]]
# name = "pg_task"
# version = "1.0.0"
# download_url_tar = "https://github.com/RekGRpth/pg_task/archive/refs/tags/v1.0.0.tar.gz"
# resolver = "pgxs"
# require_shared_preload_library = true


# TODO(yuchen): some clang warnings, but build successfully
[[plugins]]
name = "plpgsql_check"
version = "2.3.3"
download_url_tar = "https://github.com/okbob/plpgsql_check/archive/refs/tags/v2.3.3.tar.gz"
resolver = "pgxs"
require_shared_preload_library = true


# TODO(yuchen): Error - conflicting types for 'pgqr_compare' (size_t, uint64_t error)
# [[plugins]]
# name = "pg_query_rewrite"
# version = "3d4c2e33c59edd577eb7568bb8a9e396a2d1915b"
# download_url_tar = "https://github.com/pierreforstmann/pg_query_rewrite/archive/3d4c2e33c59edd577eb7568bb8a9e396a2d1915b.tar.gz"
# resolver = "pgxs"
# require_shared_preload_library = true

[[plugins]]
name = "hll"
version = "8b9821c9f7a4674cb64db977a6c89f4381d0c0d0"
download_git = { url = "https://github.com/citusdata/postgresql-hll", rev = "8b9821c" }
resolver = "pgxs"
require_shared_preload_library = true

# TODO(yuchen): Error - Failed to resolve extension name
# [[plugins]]
# name = "pg_auto_failover"
# version = "dc395982d816270ccb0c75b037f5f0f6f404e8d8"
# download_git = { url = "https://github.com/citusdata/pg_auto_failover", rev = "dc39598" }
# resolver = "pgxs"
# require_shared_preload_library = true

[[plugins]]
name = "hypopg"
version = "e7d1fea516626e752e2143bab6ebe665bc812378"
download_git = { url = "https://github.com/HypoPG/hypopg", rev = "e7d1fea" }
resolver = "pgxs"
require_shared_preload_library = true

# TODO(yuchen): Error - Failed to resolve extension name
# [[plugins]]
# name = "pgextwlist"
# version = "bee26b7e92e2d65a17e9ef26ba5803f50ff6987c"
# download_git = { url = "https://github.com/dimitri/pgextwlist", rev = "bee26b7" }
# resolver = "pgxs"
# require_shared_preload_library = true


[[plugins]]
name = "imcs"
version = "2e73bdffbde734f3fac51ec2f71a37602d4f688f"
download_git = { url = "https://github.com/knizhnik/imcs", rev = "2e73bdf" }
resolver = "pgxs"
require_shared_preload_library = true


[[plugins]]
name = "pgsentinel"
version = "fef77c8ae8061b22f12fc33872216eda5f10edc2"
download_git = { url = "https://github.com/pgsentinel/pgsentinel", rev = "fef77c8" }
resolver = "pgxs"
require_shared_preload_library = true
