[[plugin]]
name = "pgjwt"
version = "9742dab1b2f297ad3811120db7b21451bca2d3c9"
download_url = "https://github.com/michelp/pgjwt/archive/9742dab1b2f297ad3811120db7b21451bca2d3c9.tar.gz"
install_method = "pgxs"
