[package]
name = "pgextmgr"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg15"]
pg15 = ["pgx/pg15", "pgx-tests/pg15"]
pg_test = []

[dependencies]
pgx = "=0.7.4"
paste = "1"

[dev-dependencies]
pgx-tests = "=0.7.4"
